/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ASM;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class QuanLyNhanVien extends javax.swing.JFrame implements Runnable {

    List<NhanVien> list = new ArrayList<>();
    private DefaultTableModel tableModel;
    public static final String Email_Format = "\\b[\\w.%-]+@[-.\\w]+\\.[A-Za-z]{2,4}\\b";

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        Table();
        datatable();
        Clock();
    }

    // du lieu bang
    public void Table() {
        tableModel = new DefaultTableModel();
        String[] columns = {"MA", "HO VA TEN", "TUOI", "EMAIL", "LUONG"};
        tableModel.setColumnIdentifiers(columns);
        tblNhanVien.setModel(tableModel);
    }

    // check email
    public void filltable() {
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
        for (NhanVien nhanVien : list) {
            tableModel.addRow(new Object[]{nhanVien.getMaNV(), nhanVien.getHoVaTen(), nhanVien.getTuoi(), nhanVien.getEmail(), nhanVien.getLuong()});
        }
        tableModel.fireTableDataChanged();
    }

    public void datatable() {
        NhanVien nv1 = new NhanVien("ps111", "tri", 19, "tri@gmail.com", 50000000);
        list.add(nv1);
        filltable();
        Record();

    }

    public void Record() {
        SoB.setText(String.valueOf(list.size()));
    }

    public void Clock() {
        Thread time = new Thread(this);
        time.start();
    }
    // check
    boolean check;

    public void Check() {
        check = false;
        String MaNV = txtMaNV.getText();
        String HoVaTen = txtName.getText();
        String Tuoi = txtTuoi.getText();
        String Email = txtEmail.getText();
        String Luong = txtLuong.getText();

        if (MaNV.equals("")) {
            JOptionPane.showMessageDialog(this, "Dien Ma NV");
            return;
        }
        if (HoVaTen.equals("")) {
            JOptionPane.showMessageDialog(this, "Dien Ten");
            return;
        }
        if (Tuoi.equals("")) {
            JOptionPane.showMessageDialog(this, "Dien Tuoi");
            return;
        } else {
            try {
                int age = Integer.parseInt(Tuoi);
                if (age < 16 || age > 55) {
                    JOptionPane.showMessageDialog(this, "Sai Tuoi");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Loi Dinh Dang");
                return;
            }
        }
        if (Email.equals("")) {
            JOptionPane.showMessageDialog(this, "Dien Email");
            return;
        } else {
            Matcher matcherEmail = Pattern.compile(Email_Format).matcher(txtEmail.getText());
            if (!matcherEmail.matches()) {
                JOptionPane.showMessageDialog(this, "Email loi");
                return;
            }
        }
        if (Luong.equals("")) {
            JOptionPane.showMessageDialog(this, "Dien Luong");
            return;
        } else {
            try {
                Double luong = Double.parseDouble(Luong);
                if (luong < 5000) {
                    JOptionPane.showMessageDialog(this, "Sai Luong");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Luong loi");
                return;
            }
        }
        check = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDau = new javax.swing.JButton();
        btnXuong = new javax.swing.JButton();
        btnLen = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        SoA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SoB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Quan Ly Nhan Vien");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Ma Nhan Vien");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Ho Va Ten");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tuoi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Luong");

        btnDau.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDau.setText("|<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        btnXuong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnXuong.setText("<<");
        btnXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuongActionPerformed(evt);
            }
        });

        btnLen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLen.setText(">>");
        btnLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenActionPerformed(evt);
            }
        });

        btnCuoi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCuoi.setText(">|");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Record:");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtTuoi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtLuong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 51, 51));
        lblTime.setText("10:22 AM");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);

        SoA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SoA.setForeground(new java.awt.Color(255, 51, 51));
        SoA.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("of");

        SoB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SoB.setForeground(new java.awt.Color(255, 102, 102));
        SoB.setText("0");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        btnNew.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnOpen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
            .addComponent(btnFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsert)
                .addGap(19, 19, 19)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addGap(18, 18, 18)
                .addComponent(btnOpen)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTuoi)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLuong)
                    .addComponent(txtEmail)
                    .addComponent(txtMaNV)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXuong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SoB)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTime)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDau)
                            .addComponent(btnXuong)
                            .addComponent(btnLen)
                            .addComponent(btnCuoi)
                            .addComponent(jLabel7)
                            .addComponent(SoA)
                            .addComponent(jLabel9)
                            .addComponent(SoB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtMaNV.setText("");
        txtName.setText("");
        txtTuoi.setText("");
        txtEmail.setText("");
        txtLuong.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SFile.writeObject("c:/ASM/NhanVien.txt", list);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String manv = txtMaNV.getText();
        for (NhanVien nhanVien : list) {
            if (nhanVien.getMaNV().equals(manv)) {
                int Option = JOptionPane.showConfirmDialog(this, "Ban co muon update", "warning", JOptionPane.YES_NO_OPTION);
                if (Option == JOptionPane.YES_OPTION) {
                    list.remove(nhanVien);
                    filltable();
                    Record();
                    JOptionPane.showMessageDialog(this, "Xoa Thanh Cong");
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Khong tim thay nhan vien");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String manv = txtMaNV.getText();
        for (NhanVien nhanVien : list) {
            if (nhanVien.getMaNV().equals(manv)) {
                txtMaNV.setText(manv);
                txtName.setText(nhanVien.getHoVaTen());
                txtEmail.setText(nhanVien.getEmail());
                txtTuoi.setText(String.valueOf(nhanVien.getTuoi()));
                txtLuong.setText(String.valueOf(nhanVien.getLuong()));
                JOptionPane.showMessageDialog(this, "Tim Thanh Cong");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Khong tim thay nhan vien");
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        list = (List<NhanVien>) SFile.ReadObject("c:/ASM/NhanVien.txt");

        if (list.size() == 0) {
            JOptionPane.showMessageDialog(this, "Khong co nhan vien nao");
        } else {
            Record();
            filltable();
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //luu vao roi thoat ra  
        SFile.writeObject("c:/ASM/NhanVien.txt", list);
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        Check();
        if (check) {
            for (NhanVien nhanVien : list) {
                if (nhanVien.getMaNV().equals(txtMaNV.getText())) {
                    JOptionPane.showMessageDialog(this, "Ma Sinh Vien Da Ton Tai");
                    int Option = JOptionPane.showConfirmDialog(this, "Ban co muon update", "warning", JOptionPane.YES_NO_OPTION);
                    if (Option == JOptionPane.YES_OPTION) {
                        nhanVien.setHoVaTen(txtName.getText());
                        nhanVien.setTuoi(Integer.parseInt(txtTuoi.getText()));
                        nhanVien.setEmail(txtEmail.getText());
                        nhanVien.setLuong(Float.parseFloat(txtLuong.getText()));
                        JOptionPane.showMessageDialog(this, "Cap nhat thanh cong", "warning", JOptionPane.OK_OPTION);
                        filltable();

                        return;

                    }
                    return;
                }
            }

        }
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setHoVaTen(txtName.getText());
        nv.setTuoi(Integer.parseInt(txtTuoi.getText()));
        nv.setEmail(txtEmail.getText());
        nv.setLuong(Float.parseFloat(txtLuong.getText()));
        list.add(nv);
        if (check = true) {
            JOptionPane.showMessageDialog(this, "Them Thanh Cong");
            filltable();
            Record();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int select = tblNhanVien.getSelectedRow();
        index = select;
        if (select >= 0) {
            NhanVien nv = list.get(select);
            SoA.setText(String.valueOf(index+1));
            txtMaNV.setText(nv.getMaNV());
            txtName.setText(nv.getHoVaTen());
            txtTuoi.setText(String.valueOf(nv.getTuoi()));
            txtEmail.setText(nv.getEmail());
            txtLuong.setText(String.valueOf(nv.getLuong()));
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked
    int index = -1;
    private void btnLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenActionPerformed
        if (index <= list.size() - 1 && list.size() > 0) {
            if (index == list.size() - 1) {
                index = 0;
                SoA.setText(String.valueOf(index + 1));
                NhanVien nv = new NhanVien();
                nv = list.get(index);
                txtMaNV.setText(nv.getMaNV());
                txtName.setText(nv.getHoVaTen());
                txtTuoi.setText(String.valueOf(nv.getTuoi()));
                txtEmail.setText(nv.getEmail());
                txtLuong.setText(String.valueOf(nv.getLuong()));
            } else {
                index++;
                SoA.setText(String.valueOf(index + 1));
                NhanVien nv = new NhanVien();
                nv = list.get(index);
                txtMaNV.setText(nv.getMaNV());
                txtName.setText(nv.getHoVaTen());
                txtTuoi.setText(String.valueOf(nv.getTuoi()));
                txtEmail.setText(nv.getEmail());
                txtLuong.setText(String.valueOf(nv.getLuong()));
            }
        }

    }//GEN-LAST:event_btnLenActionPerformed

    private void btnXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuongActionPerformed
        if (index <= list.size() - 1 && list.size() > 0) {
            if (index == -1 || index == 0) {
                index = list.size() - 1;
                SoA.setText(String.valueOf(index + 1));
                NhanVien nv = new NhanVien();
                nv = list.get(index);
                txtMaNV.setText(nv.getMaNV());
                txtName.setText(nv.getHoVaTen());
                txtTuoi.setText(String.valueOf(nv.getTuoi()));
                txtEmail.setText(nv.getEmail());
                txtLuong.setText(String.valueOf(nv.getLuong()));
            } else {
                index--;
                SoA.setText(String.valueOf(index + 1));
                NhanVien nv = new NhanVien();
                nv = list.get(index);
                txtMaNV.setText(nv.getMaNV());
                txtName.setText(nv.getHoVaTen());
                txtTuoi.setText(String.valueOf(nv.getTuoi()));
                txtEmail.setText(nv.getEmail());
                txtLuong.setText(String.valueOf(nv.getLuong()));
            }
        }
    }//GEN-LAST:event_btnXuongActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        // TODO add your handling code here:
        index = list.size() - 1;
        SoA.setText(String.valueOf(index + 1));
        NhanVien nv = new NhanVien();
        nv = list.get(index);
        txtMaNV.setText(nv.getMaNV());
        txtName.setText(nv.getHoVaTen());
        txtTuoi.setText(String.valueOf(nv.getTuoi()));
        txtEmail.setText(nv.getEmail());
        txtLuong.setText(String.valueOf(nv.getLuong()));
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        // TODO add your handling code here:
        index = 0;
        SoA.setText(String.valueOf(index + 1));
        NhanVien nv = new NhanVien();
        nv = list.get(index);
        txtMaNV.setText(nv.getMaNV());
        txtName.setText(nv.getHoVaTen());
        txtTuoi.setText(String.valueOf(nv.getTuoi()));
        txtEmail.setText(nv.getEmail());
        txtLuong.setText(String.valueOf(nv.getLuong()));
    }//GEN-LAST:event_btnDauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SoA;
    private javax.swing.JLabel SoB;
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLen;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                Date date = new Date();
                SimpleDateFormat formater = new SimpleDateFormat();
                formater.applyPattern("hh:mm aa");
                String time = formater.format(date);
                lblTime.setText(time);
                Thread.sleep(1000);
            } catch (Exception e) {
                break;
            }
        }
    }
}
